title: Portafolio de Jon Juarez
author: Jon Juarez
email: jon.juarez@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
Afaldu denbora galdu.
theme: minima

# social links
# twitter_username: Chocu_ # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  JonJuarezz # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: true # cámbialo a false para eliminar los extractos de la página principal
